job_board/config/routes.rb
Rails.application.routes.draw do
  root to: "jobs#premium"
  resources :jobs do
    post "comments", to: "comments#create"
  end

  get 'hello/world'
  delete "comments/:id", to: "comments#destroy", as: :comment

end

job_board/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :job
	validates_presence_of :body, :job_id, :name
end

job_board/app/models/job.rb
class Job < ActiveRecord::Base
	has_many :comments
	scope :most_recent, -> {order("created_at DESC")}	
validates_presence_of :description, :title
end

job_board/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

job_board/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def comment_params
		params[:comment].permit(:name, :body)
	end

	def create
		@job = Job.find(params[:job_id])
		@comment = @job.comments.build(comment_params)
		if @comment.save
			flash[:notice] = "Comment was created with success!"
		else
			flash[:alert] = "Please fill in all fields to create a comment."
		end
		redirect_to @job
	end	

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to @comment.job, notice: "Comment destroyed with success."
	end
end

job_board/app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def world
  end
end

job_board/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.most_recent.all
  end

  def premium
      @jobs = Job.where(premium: true).most_recent.paginate(page: params[:page], per_page: 10)
    end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :premium)
    end    
end

job_board/app/helpers/application_helper.rb
module ApplicationHelper
end

job_board/app/helpers/hello_helper.rb
module HelloHelper
end

job_board/app/helpers/jobs_helper.rb
module JobsHelper
	def job_title(job)
		title = h(job.title)

		if job.premium
			title + content_tag(:strong, " (premium)")
		else
			title
		end
	end
end

job_board/app/views/comments/_comment.html.erb
<h4><%= comment.name %> said:</h4>
<%= simple_format comment.body %>
Sent <%= time_ago_in_words comment.created_at %> ago
<%= link_to "Destroy", comment_path(comment), method: :delete, confirm: "Are you sure?" %>

job_board/app/views/comments/_form.html.erb
<%= form_for [@job, Comment.new] do |f| %>
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :body %><br />
	<%= f.text_area :body %>
</div>
<div class="actions">
	<%= f.submit "Send" %>
</div>
<% end %>

job_board/app/views/hello/world.html.erb
<h1>Hello#world</h1>
<p>Find me in app/views/hello/world.html.erb</p>

job_board/app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :premium %><br>
    <%= f.check_box :premium %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

job_board/app/views/jobs/_job.html.erb
<h3><%= job_title(job) %></h3>

<%= simple_format job.description %>

<p>
	<%= pluralize(job.comments.size, "comment") %> |
	<%= link_to 'Show', job %> |
	<%= link_to 'Edit', edit_job_path(job) %> |
	<%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

job_board/app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

job_board/app/views/jobs/index.html (cópia).erb
<h1>Listing jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>
<%= link_to 'Premium jobs', root_path %>

job_board/app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

job_board/app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

job_board/app/views/jobs/premium.html.erb
<h1>Premium jobs</h1>

<%= render @jobs %>
<%= will_paginate @jobs %>

<br />

<%= link_to 'New Job', new_job_path %>
<%= link_to 'All jobs', jobs_path %>
<%= link_to 'Hello World', hello_world_path %>

job_board/app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1><%= job_title(@job) %></h1>

<%= simple_format @job.description %>

<%= pluralize(@job.comments.size, "comment") %> |
<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

<h2>Send a new comment</h2>
<%= render "comments/form" %>

<h2>Comments</h2>
<%= render @job.comments %>

job_board/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>